name: Docker publish to docker hub

on:
  release:
    types: [published]

jobs:
  docker-base-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component:
          - trivy-adapter
          - core
          - db
          - exporter
          - jobservice
          - log
          - nginx
          - notary-server
          - notary-signer
          - portal
          - prepare
          - redis
          - registry
          - registryctl

    defaults:
      run:
        working-directory: ./harbor

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
        with:
          driver: docker-container
          driver-opts: network=host
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - run: cd .. && make patch

      - name: Build base image
        uses: docker/build-push-action@v3
        with:
          context: ./harbor
          file: ./harbor/make/photon/${{ matrix.component }}/Dockerfile.base
          platforms: linux/amd64,linux/arm64
          labels: |
            org.opencontainers.image.source=https://github.com/wawa27
            org.opencontainers.image.revision=${{ github.ref_name }}
          push: true
          tags: wawa27/harbor-${{ matrix.component }}-base:${{ github.ref_name }}

  docker-image:
    needs:
      - docker-base-image

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        component:
          - prepare
          - db
          - portal
          - core
          - jobservice
          - log
          - nginx
          - registryctl
          - notary
          - trivy_adapter
          - redis
          - standalone_db_migrator
          - exporter

    defaults:
      run:
        working-directory: ./harbor

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: actions/setup-go@v3
        with:
          go-version: '^1.20.x'

      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
        with:
          driver: docker-container
          driver-opts: network=host

      - run: cd .. && make patch

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - run: cd .. && make patch

      - name: Build & Publish images
        env:
          IMAGENAMESPACE: wawa27
          BASEIMAGENAMESPACE: wawa27
          IMAGELABELS: org.opencontainers.image.source=https://github.com/wawa27/harbor-arm64
          MULTIARCH: true
          TRIVYFLAG: true
          CHARTFLAG: true
          NOTARYFLAG: true
          REGISTRYUSER: ${{ secrets.DOCKER_USERNAME }}
          REGISTRYPASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          set -eux;
          CTX="BUILDBIN=true VERSIONTAG=${{ github.ref_name }} BASEIMAGETAG=${{ github.ref_name }} MULTIARCH=${MULTIARCH} IMAGENAMESPACE=${IMAGENAMESPACE} BASEIMAGENAMESPACE=${BASEIMAGENAMESPACE} TRIVYFLAG=${TRIVYFLAG} CHARTFLAG=${CHARTFLAG} NOTARYFLAG=${CHARTFLAG} IMAGELABELS=${IMAGELABELS}"
           make versions_prepare ${CTX};
          case ${{ matrix.component }} in
            core)                   make compile_core ${CTX} ;;
            jobservice)             make compile_jobservice ${CTX};;
            registryctl)            make compile_registryctl ${CTX};;
            notary*)                make compile_notary_migrate_patch ${CTX} ;;
            standalone_db_migrator) make compile_standalone_db_migrator ${CTX} ;;
          esac;
          case ${{ matrix.component }} in
            exporter)    make build BUILDTARGET="_compile_and_build_exporter" ${CTX} ;;
            registryctl) make build BUILDTARGET="_build_registry _build_registryctl" ${CTX} ;;
            *)           make build BUILDTARGET="_build_${{ matrix.component }}" ${CTX} ;;
          esac;
